// AppModelSelfTest.swift
// Generated by Codex (gpt-5.6-terra) on 2026-09-15.

import Foundation
import Combine
import StillCore

/// Dependency-free integration checks for persistence and timer behavior in `AppModel`.
/// Invoke this from the app's `@main` entry point before `NSApplication.run()`.
@MainActor
enum AppModelSelfTest {
    static func run() -> Int32 {
        var recorder = Recorder()
        let fileManager = FileManager.default
        let root = fileManager.temporaryDirectory
            .appendingPathComponent("Still-AppModelSelfTest-\(UUID().uuidString)", isDirectory: true)

        do {
            try fileManager.createDirectory(at: root, withIntermediateDirectories: true)
            defer { try? fileManager.removeItem(at: root) }

            testCompletedFocusPersistsOnce(in: root.appendingPathComponent("completed", isDirectory: true), recorder: &recorder)
            testCustomDurationsAndSettings(in: root.appendingPathComponent("settings", isDirectory: true), recorder: &recorder)
            testPauseAndResetDoNotArchive(in: root.appendingPathComponent("cancelled", isDirectory: true), recorder: &recorder)
            testRepeatedTicksAreIdempotent(in: root.appendingPathComponent("idempotence", isDirectory: true), recorder: &recorder)
            testRunningTimerRestoresDeadline(in: root.appendingPathComponent("running", isDirectory: true), recorder: &recorder)
            testExpiredFocusCompletesOnOpen(in: root.appendingPathComponent("expired", isDirectory: true), recorder: &recorder)
            testCorruptArchiveIsPreserved(in: root.appendingPathComponent("corrupt", isDirectory: true), recorder: &recorder)
            testFocusPresetDoesNotRestart(in: root.appendingPathComponent("preset", isDirectory: true), recorder: &recorder)
            testFocusPresetPreferences(in: root.appendingPathComponent("preset-preferences", isDirectory: true), recorder: &recorder)
            testAppearancePreferences(in: root.appendingPathComponent("appearance-preferences", isDirectory: true), recorder: &recorder)
            testJournalPathAppendAndRestore(in: root.appendingPathComponent("journal", isDirectory: true), recorder: &recorder)
            testLegacyPreferencesDecode(in: root.appendingPathComponent("legacy", isDirectory: true), recorder: &recorder)
            testBackgroundJournalImportAndCompletion(in: root.appendingPathComponent("journal-worker", isDirectory: true), recorder: &recorder)
            testLocalInspiration(in: root.appendingPathComponent("inspiration", isDirectory: true), recorder: &recorder)
            testQuietClock(in: root.appendingPathComponent("quiet-clock", isDirectory: true), recorder: &recorder)
            testRestReminder(in: root.appendingPathComponent("rest-reminder", isDirectory: true), recorder: &recorder)
        } catch {
            recorder.fail("Unable to create self-test workspace: \(error)")
        }

        if recorder.failures.isEmpty {
            print("AppModel self-test passed: 16 test groups")
            return 0
        }

        print("AppModel self-test failed: \(recorder.failures.count) assertion(s)")
        for failure in recorder.failures {
            print("FAIL: \(failure)")
        }
        return 1
    }

    private static func testRestReminder(in directory: URL, recorder: inout Recorder) {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = .current
        func date(_ day: Int, _ hour: Int, _ minute: Int) -> Date {
            calendar.date(from: DateComponents(year: 2026, month: 9, day: day, hour: hour, minute: minute))!
        }
        recorder.check(!RestSchedule.contains(date(18, 21, 59), startMinute: 22 * 60, endMinute: 7 * 60, calendar: calendar),
                       "rest window: inactive before an overnight start")
        recorder.check(RestSchedule.contains(date(18, 22, 0), startMinute: 22 * 60, endMinute: 7 * 60, calendar: calendar),
                       "rest window: active at start")
        recorder.check(RestSchedule.contains(date(19, 0, 0), startMinute: 22 * 60, endMinute: 7 * 60, calendar: calendar),
                       "rest window: active across midnight")
        recorder.check(!RestSchedule.contains(date(19, 7, 0), startMinute: 22 * 60, endMinute: 7 * 60, calendar: calendar),
                       "rest window: inactive at end")
        recorder.check(!RestSchedule.contains(date(19, 0, 0), startMinute: 0, endMinute: 0, calendar: calendar),
                       "rest window: matching start and end do not create an all-day alert")

        let model = AppModel(dataDirectory: directory, preview: true)
        model.preferences.restStartMinute = 22 * 60
        model.preferences.restEndMinute = 7 * 60
        model.refreshClock(to: date(18, 23, 30))
        recorder.check(model.restReminderActive, "rest reminder: appears inside the configured window")
        model.snoozeRestReminder(at: date(18, 23, 30))
        recorder.check(!model.restReminderActive, "rest reminder: snooze hides the panel")
        model.refreshClock(to: date(18, 23, 39))
        recorder.check(!model.restReminderActive, "rest reminder: stays hidden before snooze ends")
        model.refreshClock(to: date(18, 23, 40))
        recorder.check(model.restReminderActive, "rest reminder: returns when snooze ends")
        model.refreshClock(to: date(19, 7, 0))
        recorder.check(!model.restReminderActive, "rest reminder: clears at the end of the window")

        do {
            let preferences = Preferences(restReminderEnabled: true, restStartMinute: 23 * 60 + 15,
                                          restEndMinute: 6 * 60 + 45, restMessage: "Rest tonight.")
            let restored = try JSONDecoder().decode(Preferences.self, from: JSONEncoder().encode(preferences))
            recorder.check(restored.restStartMinute == 23 * 60 + 15 && restored.restEndMinute == 6 * 60 + 45
                           && restored.restMessage == "Rest tonight.", "rest reminder: settings round trip")
        } catch { recorder.fail("rest reminder: settings round trip failed: \(error)") }
    }

    private static func testQuietClock(in directory: URL, recorder: inout Recorder) {
        let model = AppModel(dataDirectory: directory, preview: true)
        model.preferences.soundEnabled = false
        var updates = 0
        let observer = model.objectWillChange.sink { updates += 1 }
        defer { observer.cancel() }
        model.refreshClock(to: model.now.addingTimeInterval(0.25))
        recorder.check(updates == 0, "ready clock: no idle view invalidation")

        model.startFocus(minutes: 1)
        let start = model.now
        updates = 0
        for fraction in [0.25, 0.5, 0.75] { model.refreshClock(to: start.addingTimeInterval(fraction)) }
        recorder.check(updates == 0, "running clock: unchanged displayed second does not publish")
        model.refreshClock(to: start.addingTimeInterval(1))
        recorder.check(model.remaining == 59 && updates == 1, "running clock: one publication per displayed second")

        model.primaryAction()
        updates = 0
        model.refreshClock(to: model.now.addingTimeInterval(3))
        recorder.check(updates == 0, "paused clock: no idle view invalidation")
        model.primaryAction()
        let deadline = model.timer.deadline!
        model.refreshClock(to: deadline.addingTimeInterval(0.25))
        recorder.check(model.timer.phase == .completed && model.sessions.count == 1, "quiet clock: deadline still completes exactly once")
        updates = 0
        model.refreshClock(to: deadline.addingTimeInterval(10))
        recorder.check(updates == 0 && model.sessions.count == 1, "completed clock: no publication or duplicate session")
        model.refreshClock(to: Calendar.current.date(byAdding: .day, value: 1, to: model.now)!)
        recorder.check(updates == 1, "idle clock: daily statistics refresh at midnight")
    }

    private static func testCompletedFocusPersistsOnce(in directory: URL, recorder: inout Recorder) {
        let model = AppModel(dataDirectory: directory)
        prepareForTimerUse(model, focusMinutes: 1)
        model.selectMode(.focus)
        model.primaryAction()

        guard let startedAt = model.timer.startedAt else {
            recorder.fail("completed focus: timer did not start")
            return
        }
        model.advance(to: startedAt.addingTimeInterval(61))

        recorder.check(model.timer.phase == .completed, "completed focus: phase is completed")
        recorder.check(model.sessions.count == 1, "completed focus: exactly one session was added")

        let restored = AppModel(dataDirectory: directory)
        recorder.check(restored.sessions.count == 1, "completed focus: saved session restores once")
        restored.advance(to: startedAt.addingTimeInterval(120))
        recorder.check(restored.sessions.count == 1, "completed focus: restored timer does not add a duplicate")
    }

    private static func testCustomDurationsAndSettings(in directory: URL, recorder: inout Recorder) {
        let model = AppModel(dataDirectory: directory)
        model.preferences.focusMinutes = 2
        model.preferences.shortBreakMinutes = 3
        model.preferences.longBreakMinutes = 4
        model.preferences.soundEnabled = false
        model.preferences.notificationsEnabled = false
        model.preferences.floatOnTop = false
        model.preferences.theme = "dark"
        model.savePreferences()

        model.selectMode(.shortBreak)
        recorder.check(model.timer.mode == .shortBreak, "settings: selected short-break mode")
        recorder.check(model.timer.duration == 3 * 60, "settings: short-break custom duration")
        model.primaryAction()

        guard let startedAt = model.timer.startedAt else {
            recorder.fail("settings: custom break did not start")
            return
        }
        model.advance(to: startedAt.addingTimeInterval(181))
        recorder.check(model.sessions.isEmpty, "settings: completing a break never records a focus session")

        let restored = AppModel(dataDirectory: directory)
        recorder.check(restored.preferences.focusMinutes == 2, "settings: focus minutes restore")
        recorder.check(restored.preferences.shortBreakMinutes == 3, "settings: short-break minutes restore")
        recorder.check(restored.preferences.longBreakMinutes == 4, "settings: long-break minutes restore")
        recorder.check(!restored.preferences.soundEnabled, "settings: sound preference restores")
        recorder.check(!restored.preferences.notificationsEnabled, "settings: notification preference restores")
        recorder.check(!restored.preferences.floatOnTop, "settings: floating-window preference restores")
        recorder.check(restored.preferences.theme == "dark", "settings: theme restores")
    }

    private static func testPauseAndResetDoNotArchive(in directory: URL, recorder: inout Recorder) {
        let model = AppModel(dataDirectory: directory)
        prepareForTimerUse(model, focusMinutes: 1)
        model.selectMode(.focus)
        model.primaryAction()
        model.primaryAction() // Pause before the first deadline.

        recorder.check(model.timer.phase == .paused, "cancelled: primary action pauses an active focus timer")
        recorder.check(model.sessions.isEmpty, "cancelled: pausing does not archive a session")

        model.reset()
        recorder.check(model.timer.phase == .ready, "cancelled: reset returns timer to ready")
        recorder.check(model.sessions.isEmpty, "cancelled: reset does not archive a session")

        let restored = AppModel(dataDirectory: directory)
        recorder.check(restored.sessions.isEmpty, "cancelled: no session appears after restoring paused/reset timer")
    }

    private static func testRepeatedTicksAreIdempotent(in directory: URL, recorder: inout Recorder) {
        let model = AppModel(dataDirectory: directory)
        prepareForTimerUse(model, focusMinutes: 1)
        model.selectMode(.focus)
        model.primaryAction()

        guard let startedAt = model.timer.startedAt else {
            recorder.fail("idempotence: timer did not start")
            return
        }
        model.advance(to: startedAt.addingTimeInterval(61))
        model.advance(to: startedAt.addingTimeInterval(62))
        model.advance(to: startedAt.addingTimeInterval(120))

        recorder.check(model.sessions.count == 1, "idempotence: multiple ticks create one session")
        let restored = AppModel(dataDirectory: directory)
        restored.advance(to: startedAt.addingTimeInterval(180))
        recorder.check(restored.sessions.count == 1, "idempotence: restored completed timer remains single-session")
    }

    private static func testRunningTimerRestoresDeadline(in directory: URL, recorder: inout Recorder) {
        let baseline = Date(timeIntervalSince1970: floor(Date().timeIntervalSince1970) - 30)
        var timer = TimerState(mode: .focus, duration: 120)
        timer.start(at: baseline)

        var preferences = Preferences()
        preferences.soundEnabled = false
        preferences.notificationsEnabled = false
        let archive = LocalArchive(timer: timer, sessions: [], preferences: preferences)

        do {
            try write(archive: archive, to: archiveURL(in: directory))
            let model = AppModel(dataDirectory: directory)
            let expectedDeadline = baseline.addingTimeInterval(120)

            recorder.check(model.timer.phase == .running, "running restore: timer remains running")
            recorder.check(
                approximately(model.timer.remaining(at: expectedDeadline.addingTimeInterval(-20)), 20),
                "running restore: remaining time derives from saved deadline"
            )
            model.advance(to: expectedDeadline.addingTimeInterval(1))
            recorder.check(model.sessions.count == 1, "running restore: elapsed saved timer records one session")
        } catch {
            recorder.fail("running restore: could not write or load archive: \(error)")
        }
    }

    private static func testExpiredFocusCompletesOnOpen(in directory: URL, recorder: inout Recorder) {
        let baseline = Date(timeIntervalSince1970: floor(Date().timeIntervalSince1970) - 120)
        var timer = TimerState(mode: .focus, duration: 60)
        timer.start(at: baseline)

        var preferences = Preferences()
        preferences.soundEnabled = false
        preferences.notificationsEnabled = false
        let archive = LocalArchive(timer: timer, sessions: [], preferences: preferences)

        do {
            try write(archive: archive, to: archiveURL(in: directory))
            let model = AppModel(dataDirectory: directory)
            recorder.check(model.timer.phase == .completed, "expired open: elapsed focus timer completes during load")
            recorder.check(model.sessions.count == 1, "expired open: elapsed focus timer adds one session")

            let restored = AppModel(dataDirectory: directory)
            recorder.check(restored.sessions.count == 1, "expired open: reconciled session persists once")
        } catch {
            recorder.fail("expired open: could not write or load archive: \(error)")
        }
    }

    private static func testCorruptArchiveIsPreserved(in directory: URL, recorder: inout Recorder) {
        let original = Data("{this is not valid Still state".utf8)
        let stateURL = archiveURL(in: directory)

        do {
            try FileManager.default.createDirectory(at: stateURL.deletingLastPathComponent(), withIntermediateDirectories: true)
            try original.write(to: stateURL, options: .atomic)

            let model = AppModel(dataDirectory: directory)
            recorder.check(model.storageError != nil, "corrupt archive: reports a storage error")

            let contents = try FileManager.default.contentsOfDirectory(
                at: stateURL.deletingLastPathComponent(),
                includingPropertiesForKeys: nil
            )
            let backups = contents.filter { $0.lastPathComponent.hasPrefix("state-unreadable-") }
            recorder.check(backups.count == 1, "corrupt archive: creates one backup")
            if let backup = backups.first {
                recorder.check(try Data(contentsOf: backup) == original, "corrupt archive: backup preserves exact bytes")
            }
            recorder.check(try Data(contentsOf: stateURL) == original, "corrupt archive: original stays untouched")

            model.reset()
            model.persist()
            let repaired = try Data(contentsOf: stateURL)
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .iso8601
            _ = try decoder.decode(LocalArchive.self, from: repaired)
            recorder.check(repaired != original, "corrupt archive: successful backup permits a fresh state to be saved")
            if let backup = backups.first {
                recorder.check(try Data(contentsOf: backup) == original, "corrupt archive: backup stays immutable after recovery")
            }
        } catch {
            recorder.fail("corrupt archive: fixture failed: \(error)")
        }
    }

    private static func testFocusPresetDoesNotRestart(in directory: URL, recorder: inout Recorder) {
        let model = AppModel(dataDirectory: directory)
        prepareForTimerUse(model, focusMinutes: 25)

        model.startFocus(minutes: 50)
        let originalDeadline = model.timer.deadline
        let originalSessionID = model.timer.sessionID
        model.startFocus(minutes: 25)

        recorder.check(model.timer.phase == .running, "preset: 50-minute start begins focus")
        recorder.check(model.timer.mode == .focus, "preset: start remains in focus mode")
        recorder.check(model.timer.duration == 50 * 60, "preset: 50-minute duration is applied")
        recorder.check(model.timer.deadline == originalDeadline, "preset: start is ignored while timer is in progress")
        recorder.check(model.timer.sessionID == originalSessionID, "preset: in-progress start keeps session identity")
    }

    private static func testFocusPresetPreferences(in directory: URL, recorder: inout Recorder) {
        let defaults = Preferences()
        recorder.check(defaults.focusMinutes == 30, "preset preferences: default focus duration is 30 minutes")
        recorder.check(defaults.focusPresets == [30, 45, 60], "preset preferences: default slots are 30, 45, and 60 minutes")

        let maximumScale = Preferences(compactScale: 3.0)
        recorder.check(maximumScale.compactScale == 3.0, "compact scale: initializer preserves 3.0")
        recorder.check(Preferences(compactScale: 4.0).compactScale == 3.0, "compact scale: initializer clamps 4.0 to 3.0")

        do {
            let encoded = try JSONEncoder().encode(maximumScale)
            let encodedScale = try JSONSerialization.jsonObject(with: encoded) as? [String: Any]
            recorder.check(encodedScale?["compactScale"] as? Double == 3.0, "compact scale: encoding preserves 3.0")

            let decoded = try JSONDecoder().decode(Preferences.self, from: encoded)
            recorder.check(decoded.compactScale == 3.0, "compact scale: decoding preserves 3.0")
        } catch {
            recorder.fail("compact scale: preference round trip failed: \(error)")
        }

        let scalePersistenceDirectory = directory.appendingPathComponent("scale-persistence", isDirectory: true)
        let scaleModel = AppModel(dataDirectory: scalePersistenceDirectory)
        scaleModel.preferences.compactScale = 3.0
        scaleModel.savePreferences()
        let restoredScaleModel = AppModel(dataDirectory: scalePersistenceDirectory)
        recorder.check(restoredScaleModel.preferences.compactScale == 3.0, "compact scale: persistence preserves 3.0")

        let clamped = Preferences(focusPresets: [0, 500])
        recorder.check(clamped.focusPresets == [1, 180, 60], "preset preferences: short out-of-range arrays clamp and fill by slot")

        do {
            let encoded = try JSONEncoder().encode(Preferences(focusPresets: [37, 37, 120]))
            let decoded = try JSONDecoder().decode(Preferences.self, from: encoded)
            recorder.check(decoded.focusPresets == [37, 37, 120], "preset preferences: round trip preserves slot order and duplicates")
        } catch {
            recorder.fail("preset preferences: preference round trip failed: \(error)")
        }

        for (slot, minutes) in defaults.focusPresets.enumerated() {
            let presetModel = AppModel(dataDirectory: directory.appendingPathComponent("slot-\(slot)", isDirectory: true))
            presetModel.startFocus(minutes: minutes)
            recorder.check(
                presetModel.timer.duration == Double(minutes * 60),
                "preset preferences: slot \(slot + 1) starts a \(minutes)-minute focus timer"
            )
        }

        let model = AppModel(dataDirectory: directory.appendingPathComponent("persistence", isDirectory: true))
        model.preferences.focusPresets = [37, 37, 120]
        model.savePreferences()
        model.startFocus(minutes: 37)
        guard let originalDeadline = model.timer.deadline, let originalSessionID = model.timer.sessionID else {
            recorder.fail("preset preferences: persisted focus timer did not start")
            return
        }

        model.preferences.focusPresets = [40, 40, 120]
        model.savePreferences()

        recorder.check(model.timer.deadline == originalDeadline, "preset preferences: saving while active keeps the deadline")
        recorder.check(model.timer.sessionID == originalSessionID, "preset preferences: saving while active keeps the session identity")

        let restored = AppModel(dataDirectory: directory.appendingPathComponent("persistence", isDirectory: true))
        recorder.check(restored.preferences.focusPresets == [40, 40, 120], "preset preferences: saved slots restore in order with duplicates")
    }

    private static func testAppearancePreferences(in directory: URL, recorder: inout Recorder) {
        let defaults = Preferences()
        recorder.check(defaults.colorTheme == "sage", "appearance preferences: default color theme is sage")
        recorder.check(defaults.edgeStyle == "glass", "appearance preferences: default edge style is glass")

        var normalized = Preferences(colorTheme: "OCEAN", edgeStyle: "DIFFUSE")
        recorder.check(normalized.colorTheme == "ocean", "appearance preferences: initializer lowercases color theme")
        recorder.check(normalized.edgeStyle == "diffuse", "appearance preferences: initializer lowercases edge style")
        normalized.colorTheme = "unknown"
        normalized.edgeStyle = "blurred"
        normalized.sanitize()
        recorder.check(normalized.colorTheme == "sage", "appearance preferences: invalid color theme falls back to sage")
        recorder.check(normalized.edgeStyle == "glass", "appearance preferences: invalid edge style falls back to glass")

        let colorThemes = ["sage", "ocean", "lavender", "rose", "sand", "clay", "graphite", "mint"]
        for colorTheme in colorThemes {
            do {
                let encoded = try JSONEncoder().encode(Preferences(colorTheme: colorTheme))
                let decoded = try JSONDecoder().decode(Preferences.self, from: encoded)
                recorder.check(decoded.colorTheme == colorTheme, "appearance preferences: \(colorTheme) survives a round trip")
            } catch {
                recorder.fail("appearance preferences: \(colorTheme) round trip failed: \(error)")
            }
        }

        let model = AppModel(dataDirectory: directory.appendingPathComponent("persistence", isDirectory: true))
        prepareForTimerUse(model, focusMinutes: 37)
        model.preferences.edgeStyle = "DIFFUSE"
        model.startFocus(minutes: 37)
        guard let deadline = model.timer.deadline, let sessionID = model.timer.sessionID else {
            recorder.fail("appearance preferences: focus timer did not start")
            return
        }
        model.savePreferences()
        recorder.check(model.timer.deadline == deadline, "appearance preferences: saving preserves a running deadline")
        recorder.check(model.timer.sessionID == sessionID, "appearance preferences: saving preserves a running session identity")

        let restored = AppModel(dataDirectory: directory.appendingPathComponent("persistence", isDirectory: true))
        recorder.check(restored.preferences.edgeStyle == "diffuse", "appearance preferences: diffuse edge style restores")
        // Recovery archives store ISO-8601 timestamps at whole-second precision.
        let archivedDeadline = Date(timeIntervalSince1970: floor(deadline.timeIntervalSince1970))
        recorder.check(restored.timer.deadline == archivedDeadline, "appearance preferences: persisted timer deadline restores")
        recorder.check(restored.timer.sessionID == sessionID, "appearance preferences: persisted timer session identity restores")
    }

    private static func testJournalPathAppendAndRestore(in directory: URL, recorder: inout Recorder) {
        let stateDirectory = directory.appendingPathComponent("state", isDirectory: true)
        let journalURL = directory.appendingPathComponent("sessions.md")
        let model = AppModel(dataDirectory: stateDirectory)
        prepareForTimerUse(model, focusMinutes: 1)

        var pathSaved: Bool?
        Task { pathSaved = await model.setJournalPathAsync(journalURL.path) }
        recorder.check(waitUntil { pathSaved != nil } && pathSaved == true, "journal: async path selection accepts a writable Markdown file")
        model.startFocus(minutes: 1)
        guard let startedAt = model.timer.startedAt else {
            recorder.fail("journal: focus timer did not start")
            return
        }
        model.advance(to: startedAt.addingTimeInterval(61))
        recorder.check(waitForJournal(model), "journal: completion finishes its background write")

        do {
            let written = try MarkdownJournal.read(from: journalURL)
            recorder.check(model.sessions.count == 1, "journal: completed focus remains in local archive")
            recorder.check(written.count == 1, "journal: completed focus appends one Markdown row")
            recorder.check(written.first?.id == model.sessions.first?.id, "journal: Markdown row has local session identity")

            let restored = AppModel(dataDirectory: stateDirectory)
            recorder.check(waitForJournal(restored), "journal: restore finishes before synchronous CLI path change")
            recorder.check(restored.sessions.count == 1, "journal: local archive restores one session")
            recorder.check(try MarkdownJournal.read(from: journalURL).count == 1, "journal: restore does not duplicate Markdown rows")
            recorder.check(restored.setJournalPath(journalURL.path), "journal: resetting the same path succeeds")
            recorder.check(try MarkdownJournal.read(from: journalURL).count == 1, "journal: resetting the path remains idempotent")
        } catch {
            recorder.fail("journal: could not read persisted Markdown: \(error)")
        }
    }

    private static func testLegacyPreferencesDecode(in directory: URL, recorder: inout Recorder) {
        let legacyJSON = Data("""
        {
          "focusMinutes": 48,
          "shortBreakMinutes": 7,
          "longBreakMinutes": 21,
          "soundEnabled": false,
          "notificationsEnabled": false,
          "floatOnTop": false,
          "theme": "dusk"
        }
        """.utf8)

        do {
            let preferences = try JSONDecoder().decode(Preferences.self, from: legacyJSON)
            recorder.check(preferences.focusMinutes == 48, "legacy preferences: focus duration is retained")
            recorder.check(preferences.focusPresets == [30, 45, 60], "legacy preferences: missing preset slots default")
            recorder.check(preferences.shortBreakMinutes == 7, "legacy preferences: short-break duration is retained")
            recorder.check(preferences.longBreakMinutes == 21, "legacy preferences: long-break duration is retained")
            recorder.check(preferences.theme == "system", "legacy preferences: v1 theme maps to system")
            recorder.check(preferences.colorTheme == "sage", "legacy preferences: missing color theme defaults to sage")
            recorder.check(preferences.edgeStyle == "glass", "legacy preferences: missing edge style defaults to glass")
            recorder.check(preferences.compactScale == 1, "legacy preferences: missing compact scale defaults")
            recorder.check(preferences.backgroundOpacity == 0.5, "legacy preferences: missing opacity defaults")
            recorder.check(preferences.journalPath.isEmpty, "legacy preferences: missing journal path defaults empty")
        } catch {
            recorder.fail("legacy preferences: decoding failed: \(error)")
        }
    }

    private static func testBackgroundJournalImportAndCompletion(in directory: URL, recorder: inout Recorder) {
        let stateDirectory = directory.appendingPathComponent("state", isDirectory: true)
        let journalURL = directory.appendingPathComponent("sessions.md")
        let imported = FocusSession(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000011")!,
            startedAt: Date(timeIntervalSince1970: 1_789_000_000),
            completedAt: Date(timeIntervalSince1970: 1_789_001_500),
            duration: 1_500
        )
        let baseline = Date(timeIntervalSince1970: floor(Date().timeIntervalSince1970) - 30)
        var timer = TimerState(mode: .focus, duration: 60)
        timer.start(at: baseline)

        var preferences = Preferences()
        preferences.soundEnabled = false
        preferences.notificationsEnabled = false
        preferences.journalPath = journalURL.path
        let archive = LocalArchive(timer: timer, sessions: [], preferences: preferences)

        do {
            try MarkdownJournal.synchronize(sessions: [imported], to: journalURL)
            try write(archive: archive, to: archiveURL(in: stateDirectory))

            let model = AppModel(dataDirectory: stateDirectory)
            model.advance(to: baseline.addingTimeInterval(61))
            recorder.check(waitForJournal(model), "journal worker: background import/sync reached idle state")

            let ids = Set(model.sessions.map(\.id))
            recorder.check(ids.contains(imported.id), "journal worker: existing Markdown session imports into cache")
            recorder.check(model.sessions.count == 2, "journal worker: completion during startup sync is retained")
            let journal = try MarkdownJournal.read(from: journalURL)
            recorder.check(journal.count == 2, "journal worker: Markdown receives imported and newly completed sessions")
            recorder.check(Set(journal.map(\.id)) == ids, "journal worker: journal and cache IDs agree")
        } catch {
            recorder.fail("journal worker: fixture failed: \(error)")
        }
    }

    private static func testLocalInspiration(in directory: URL, recorder: inout Recorder) {
        do {
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            let url = directory.appendingPathComponent("inspiration.json")
            let catalog = InspirationCatalog(phrases: [
                Inspiration(id: "first", text: "One small step.", source: "Local notes"),
                Inspiration(id: "second", text: "A second thought.")
            ])
            try catalog.encoded().write(to: url)
            let store = InspirationStore(directory: directory)
            store.reload()
            recorder.check(waitUntil { !store.isLoading }, "inspiration: background load completes")
            recorder.check(store.current.id == "first", "inspiration: local catalog loads")
            store.advance()
            recorder.check(store.current.id == "second", "inspiration: explicit next advances once")
            store.reload()
            recorder.check(waitUntil { !store.isLoading }, "inspiration: reload completes")
            recorder.check(store.current.id == "second", "inspiration: reopening retains current thought")
            let broken = Data("{unfinished edit".utf8)
            try broken.write(to: url)
            store.reload()
            recorder.check(waitUntil { !store.isLoading }, "inspiration: invalid file load returns")
            recorder.check(store.error != nil && store.current.id == "second", "inspiration: invalid edits keep last good thought")
            recorder.check(try Data(contentsOf: url) == broken, "inspiration: invalid source is preserved")
            try catalog.encoded().write(to: url)
            store.reload()
            recorder.check(waitUntil { !store.isLoading }, "inspiration: repaired file loads")
            recorder.check(store.error == nil, "inspiration: repaired edits clear error")
            store.advance()
            recorder.check(store.current.id == "first", "inspiration: next wraps without a duplicate")
        } catch { recorder.fail("inspiration: fixture failed: \(error)") }
    }

    private static func prepareForTimerUse(_ model: AppModel, focusMinutes: Int) {
        model.preferences.focusMinutes = focusMinutes
        model.preferences.soundEnabled = false
        model.preferences.notificationsEnabled = false
        model.savePreferences()
    }

    private static func archiveURL(in dataDirectory: URL) -> URL {
        dataDirectory
            .appendingPathComponent("state.json")
    }

    private static func write(archive: LocalArchive, to url: URL) throws {
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        try encoder.encode(archive).write(to: url, options: .atomic)
    }

    private static func approximately(_ actual: TimeInterval, _ expected: TimeInterval, tolerance: TimeInterval = 0.01) -> Bool {
        abs(actual - expected) <= tolerance
    }

    private static func waitForJournal(_ model: AppModel) -> Bool {
        waitUntil { !model.journalIsBusy }
    }

    private static func waitUntil(timeout: TimeInterval = 2, _ condition: () -> Bool) -> Bool {
        let deadline = Date().addingTimeInterval(timeout)
        while !condition() && Date() < deadline {
            RunLoop.main.run(until: Date().addingTimeInterval(0.01))
        }
        return condition()
    }

    private struct Recorder {
        var failures: [String] = []

        mutating func check(_ condition: @autoclosure () throws -> Bool, _ message: String) {
            do {
                if try !condition() {
                    fail(message)
                }
            } catch {
                fail("\(message): \(error)")
            }
        }

        mutating func fail(_ message: String) {
            failures.append(message)
        }
    }
}
