// WindowSelfTest.swift
// Generated by Codex (gpt-5.6-terra) on 2026-09-15.

import AppKit
import Foundation

/// Regression coverage for compact-panel resizing without synthesizing user input.
@MainActor
enum WindowSelfTest {
    static func run(
        panel: NSPanel,
        setScale: (Double) -> Void,
        setExpanded: (Bool) -> Void,
        flushPreferences: () -> Void
    ) async -> Int32 {
        var failures: [String] = []

        guard let screen = NSScreen.main ?? panel.screen ?? NSScreen.screens.first else {
            print("Window self-test failed: no screen available")
            return 1
        }

        center(panel: panel, in: screen.visibleFrame)
        panel.orderFrontRegardless()
        await settle()

        let initialAnchor = anchor(of: panel.frame)
        check(
            isAwayFromScreenEdges(initialAnchor, in: screen.visibleFrame),
            "centered panel anchor is too close to a visible-frame edge",
            failures: &failures
        )

        await applyScale(
            0.8,
            panel: panel,
            setScale: setScale,
            flushPreferences: flushPreferences,
            expectedAnchor: initialAnchor,
            label: "first compact resize",
            failures: &failures
        )
        let firstResizeAnchor = anchor(of: panel.frame)
        check(
            sameAnchor(firstResizeAnchor, initialAnchor),
            "first compact resize moved the centered top-left anchor",
            failures: &failures
        )

        for cycle in 1...3 {
            for scale in [0.8, 1.4, 1.0, 0.85, 0.8] {
                await applyScale(
                    scale,
                    panel: panel,
                    setScale: setScale,
                    flushPreferences: flushPreferences,
                    expectedAnchor: firstResizeAnchor,
                    label: "cycle \(cycle), scale \(scale)",
                    failures: &failures
                )
            }
        }

        // Exercise the same deferred, coalesced preference path used by rapid slider
        // changes. There is deliberately no explicit flush before this settle.
        setScale(0.85)
        setScale(1.4)
        setScale(0.8)
        await settle()
        checkWindow(
            panel,
            expectedSize: compactSize(for: 0.8),
            expectedAnchor: firstResizeAnchor,
            label: "coalesced deferred scale updates",
            failures: &failures
        )

        setExpanded(true)
        flushPreferences()
        await settle(for: 400)
        checkWindow(
            panel,
            expectedSize: NSSize(width: 256, height: 274),
            expectedAnchor: nil,
            label: "expanded panel",
            failures: &failures
        )

        setScale(1.4)
        flushPreferences()
        await settle()
        checkWindow(
            panel,
            expectedSize: NSSize(width: 256, height: 274),
            expectedAnchor: nil,
            label: "expanded panel after scale change",
            failures: &failures
        )

        setExpanded(false)
        flushPreferences()
        await settle(for: 400)
        checkWindow(
            panel,
            expectedSize: compactSize(for: 1.4),
            expectedAnchor: firstResizeAnchor,
            label: "collapse after expanded scale change",
            failures: &failures
        )

        await applyScale(
            0.8,
            panel: panel,
            setScale: setScale,
            flushPreferences: flushPreferences,
            expectedAnchor: firstResizeAnchor,
            label: "final compact scale",
            failures: &failures
        )

        // Interrupt both directions of the native transition. At the 50 ms samples
        // the panel may legitimately be between compact and expanded dimensions, so
        // only verify that it remains present, finite, and inside a visible screen.
        setExpanded(true)
        flushPreferences()
        await settle(for: 50)
        checkWindow(
            panel,
            expectedSize: nil,
            expectedAnchor: nil,
            label: "rapid reversal while expanding",
            failures: &failures
        )

        setExpanded(false)
        flushPreferences()
        await settle(for: 50)
        checkWindow(
            panel,
            expectedSize: nil,
            expectedAnchor: nil,
            label: "rapid reversal while collapsing",
            failures: &failures
        )

        setExpanded(true)
        flushPreferences()
        await settle(for: 400)
        checkWindow(
            panel,
            expectedSize: NSSize(width: 256, height: 274),
            expectedAnchor: nil,
            label: "rapid reversal settled expanded",
            failures: &failures
        )

        setScale(0.85)
        flushPreferences()
        await settle()
        setExpanded(false)
        flushPreferences()
        await settle(for: 400)
        checkWindow(
            panel,
            expectedSize: compactSize(for: 0.85),
            expectedAnchor: firstResizeAnchor,
            label: "rapid reversal collapsed selected compact size",
            failures: &failures
        )

        if failures.isEmpty {
            print("Window self-test passed: 4 groups")
            return 0
        }

        print("Window self-test failed: \(failures.count) assertion(s)")
        for failure in failures {
            print("FAIL: \(failure)")
        }
        return 1
    }

    private static func applyScale(
        _ scale: Double,
        panel: NSPanel,
        setScale: (Double) -> Void,
        flushPreferences: () -> Void,
        expectedAnchor: Anchor,
        label: String,
        failures: inout [String]
    ) async {
        setScale(scale)
        flushPreferences()
        await settle()
        checkWindow(
            panel,
            expectedSize: compactSize(for: scale),
            expectedAnchor: expectedAnchor,
            label: label,
            failures: &failures
        )
    }

    private static func center(panel: NSPanel, in visibleFrame: NSRect) {
        var frame = panel.frame
        frame.origin = NSPoint(
            x: (visibleFrame.midX - frame.width / 2).rounded(),
            y: (visibleFrame.midY - frame.height / 2).rounded()
        )
        panel.setFrame(frame, display: true, animate: false)
    }

    private static func settle(for milliseconds: UInt64 = 100) async {
        try? await Task.sleep(nanoseconds: milliseconds * 1_000_000)
        await Task.yield()
    }

    private static func checkWindow(
        _ panel: NSPanel,
        expectedSize: NSSize?,
        expectedAnchor: Anchor?,
        label: String,
        failures: inout [String]
    ) {
        let frame = panel.frame
        let finite = frame.origin.x.isFinite && frame.origin.y.isFinite && frame.width.isFinite && frame.height.isFinite
        check(finite && frame.width > 0 && frame.height > 0, "\(label): panel frame is not finite and nonempty", failures: &failures)
        check(panel.isVisible, "\(label): panel is no longer visible", failures: &failures)
        check(!panel.isMiniaturized, "\(label): panel became miniaturized", failures: &failures)

        if let expectedSize {
            check(
                approximately(frame.width, expectedSize.width) && approximately(frame.height, expectedSize.height),
                "\(label): expected \(Int(expectedSize.width))×\(Int(expectedSize.height)), got \(frame.width)×\(frame.height)",
                failures: &failures
            )
        }

        if let expectedAnchor {
            check(sameAnchor(anchor(of: frame), expectedAnchor), "\(label): top-left anchor drifted by more than 1 point", failures: &failures)
        }

        guard let host = panel.contentView else {
            failures.append("\(label): panel has no hosting view")
            return
        }
        let bounds = host.bounds
        check(!host.isHidden, "\(label): hosting view is hidden", failures: &failures)
        check(
            approximately(bounds.width, frame.width) && approximately(bounds.height, frame.height),
            "\(label): host bounds \(bounds.width)×\(bounds.height) do not match panel frame \(frame.width)×\(frame.height)",
            failures: &failures
        )

        let isContained = NSScreen.screens.contains { screen in
            screen.visibleFrame.insetBy(dx: -1, dy: -1).contains(frame)
        }
        check(isContained, "\(label): panel is outside every visible screen frame", failures: &failures)
    }

    private static func compactSize(for scale: Double) -> NSSize {
        NSSize(width: (128 * scale).rounded(), height: (52 * scale).rounded())
    }

    private static func anchor(of frame: NSRect) -> Anchor {
        Anchor(x: frame.minX, top: frame.maxY)
    }

    private static func sameAnchor(_ lhs: Anchor, _ rhs: Anchor) -> Bool {
        approximately(lhs.x, rhs.x) && approximately(lhs.top, rhs.top)
    }

    private static func isAwayFromScreenEdges(_ anchor: Anchor, in visibleFrame: NSRect) -> Bool {
        anchor.x > visibleFrame.minX + 8 && anchor.x < visibleFrame.maxX - 8 &&
        anchor.top > visibleFrame.minY + 8 && anchor.top < visibleFrame.maxY - 8
    }

    private static func approximately(_ lhs: CGFloat, _ rhs: CGFloat, tolerance: CGFloat = 1) -> Bool {
        abs(lhs - rhs) <= tolerance
    }

    private static func check(_ condition: @autoclosure () -> Bool, _ message: String, failures: inout [String]) {
        if !condition() {
            failures.append(message)
        }
    }

    private struct Anchor {
        let x: CGFloat
        let top: CGFloat
    }
}
