#!/bin/sh
# test.sh
# Generated by Codex (gpt-5.6-terra) on 2026-09-15.
# Runs the dependency-free StillCore test suite without Swift Package Manager or XCTest.

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
TEMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/still-core-tests.XXXXXX")
trap 'rm -rf "$TEMP_DIR"' EXIT HUP INT TERM

swiftc \
    "$PROJECT_ROOT/Sources/StillCore/StillCore.swift" \
    "$SCRIPT_DIR/test-core.swift" \
    -o "$TEMP_DIR/test-core"

"$TEMP_DIR/test-core"
