// test-core.swift
// Generated by Codex (gpt-5.6-terra) on 2026-09-15.

import Foundation

/// Dependency-free verification for StillCore when XCTest is unavailable.
@main
struct StillCoreTestRunner {
    private static let origin = Date(timeIntervalSinceReferenceDate: 1_000_000)

    static func main() {
        var failures = 0

        testModeMetadata(failures: &failures)
        testStartAndRepeatedStart(failures: &failures)
        testPauseAndResume(failures: &failures)
        testFocusCompletionIsIdempotent(failures: &failures)
        testRestoredCompletionDoesNotDuplicate(failures: &failures)
        testRunningTimerRestoresDeadline(failures: &failures)
        testResetAndReconfigure(failures: &failures)
        testBreakDoesNotCreateSession(failures: &failures)
        testElapsedPauseCanStillDeliverOneSession(failures: &failures)
        testInvalidAndCorruptStateNormalization(failures: &failures)

        if failures == 0 {
            print("StillCore checks passed: 10 test groups")
        } else {
            print("StillCore checks failed: \(failures) assertion(s)")
            exit(1)
        }
    }

    private static func testModeMetadata(failures: inout Int) {
        check(TimerMode.focus.title == "Focus", "focus title", failures: &failures)
        check(TimerMode.shortBreak.title == "Short Break", "short-break title", failures: &failures)
        check(TimerMode.longBreak.title == "Long Break", "long-break title", failures: &failures)
        check(TimerMode.focus.defaultDuration == 30 * 60, "focus default duration", failures: &failures)
        check(TimerMode.shortBreak.defaultDuration == 5 * 60, "short-break default duration", failures: &failures)
        check(TimerMode.longBreak.defaultDuration == 15 * 60, "long-break default duration", failures: &failures)
    }

    private static func testStartAndRepeatedStart(failures: inout Int) {
        var timer = TimerState(mode: .focus, duration: 120)
        timer.start(at: origin)
        let firstDeadline = timer.deadline
        let firstSessionID = timer.sessionID

        timer.start(at: origin.addingTimeInterval(30))

        check(timer.phase == .running, "start marks timer running", failures: &failures)
        check(timer.startedAt == origin, "start stores origin", failures: &failures)
        check(timer.deadline == origin.addingTimeInterval(120), "start uses absolute deadline", failures: &failures)
        check(timer.deadline == firstDeadline, "repeated start leaves deadline unchanged", failures: &failures)
        check(timer.sessionID == firstSessionID, "repeated start leaves session identity unchanged", failures: &failures)
        check(approximately(timer.remaining(at: origin.addingTimeInterval(35)), 85), "remaining derives from deadline", failures: &failures)
    }

    private static func testPauseAndResume(failures: inout Int) {
        var timer = TimerState(mode: .focus, duration: 120)
        timer.start(at: origin)
        timer.pause(at: origin.addingTimeInterval(30))

        check(timer.phase == .paused, "pause changes phase", failures: &failures)
        check(approximately(timer.remaining, 90), "pause stores remaining time", failures: &failures)
        check(timer.deadline == nil, "pause clears deadline", failures: &failures)
        check(timer.startedAt == origin, "pause keeps original startedAt", failures: &failures)

        let resumedAt = origin.addingTimeInterval(1_000)
        timer.start(at: resumedAt)
        check(timer.phase == .running, "resume changes phase", failures: &failures)
        check(timer.startedAt == origin, "resume retains original startedAt", failures: &failures)
        check(timer.deadline == resumedAt.addingTimeInterval(90), "resume creates a new absolute deadline", failures: &failures)
        check(approximately(timer.remaining(at: resumedAt.addingTimeInterval(20)), 70), "resumed timer counts down", failures: &failures)
    }

    private static func testFocusCompletionIsIdempotent(failures: inout Int) {
        var timer = TimerState(mode: .focus, duration: 120)
        timer.start(at: origin)
        let id = timer.sessionID

        check(timer.tick(at: origin.addingTimeInterval(119)) == nil, "timer does not complete early", failures: &failures)
        let session = timer.tick(at: origin.addingTimeInterval(200))

        check(timer.phase == .completed, "deadline completes focus timer", failures: &failures)
        check(timer.remaining == 0, "completed timer has no remaining time", failures: &failures)
        check(session?.id == id, "completed session keeps timer identity", failures: &failures)
        check(session?.startedAt == origin, "session has original start", failures: &failures)
        check(session?.completedAt == origin.addingTimeInterval(120), "session completes at deadline after sleep", failures: &failures)
        check(session?.duration == 120, "session records planned duration", failures: &failures)
        check(timer.tick(at: origin.addingTimeInterval(201)) == nil, "repeated tick cannot duplicate session", failures: &failures)
    }

    private static func testRestoredCompletionDoesNotDuplicate(failures: inout Int) {
        var timer = TimerState(mode: .focus, duration: 60)
        timer.start(at: origin)
        let emitted = timer.tick(at: origin.addingTimeInterval(61))
        check(emitted != nil, "source completion emits a session", failures: &failures)

        do {
            let data = try JSONEncoder().encode(timer)
            var restored = try JSONDecoder().decode(TimerState.self, from: data)
            check(restored.phase == .completed, "completed state restores", failures: &failures)
            check(restored.tick(at: origin.addingTimeInterval(100)) == nil, "restored completion cannot duplicate session", failures: &failures)
        } catch {
            fail("completion round-trip threw \(error)", failures: &failures)
        }
    }

    private static func testRunningTimerRestoresDeadline(failures: inout Int) {
        var timer = TimerState(mode: .focus, duration: 120)
        timer.start(at: origin)
        _ = timer.tick(at: origin.addingTimeInterval(30))

        do {
            let encoder = JSONEncoder()
            encoder.dateEncodingStrategy = .iso8601
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .iso8601
            var restored = try decoder.decode(TimerState.self, from: encoder.encode(timer))

            check(restored.phase == .running, "running state restores", failures: &failures)
            check(approximately(restored.remaining(at: origin.addingTimeInterval(80)), 40), "restored timer retains absolute deadline", failures: &failures)
            check(restored.tick(at: origin.addingTimeInterval(121)) != nil, "restored timer completes", failures: &failures)
        } catch {
            fail("running-timer round-trip threw \(error)", failures: &failures)
        }
    }

    private static func testResetAndReconfigure(failures: inout Int) {
        var timer = TimerState(mode: .focus, duration: 90)
        timer.start(at: origin)
        timer.reset()

        check(timer.phase == .ready, "reset makes timer ready", failures: &failures)
        check(timer.remaining == 90, "reset restores full duration", failures: &failures)
        check(timer.startedAt == nil && timer.deadline == nil && timer.sessionID == nil, "reset clears interval metadata", failures: &failures)

        timer.configure(mode: .longBreak, duration: 45)
        check(timer.mode == .longBreak, "configure selects requested mode", failures: &failures)
        check(timer.duration == 45 && timer.remaining == 45, "configure uses requested duration", failures: &failures)
        check(timer.phase == .ready, "configure cancels existing interval", failures: &failures)
    }

    private static func testBreakDoesNotCreateSession(failures: inout Int) {
        var timer = TimerState(mode: .shortBreak, duration: 20)
        timer.start(at: origin)

        check(timer.sessionID == nil, "break has no focus session ID", failures: &failures)
        check(timer.tick(at: origin.addingTimeInterval(20)) == nil, "break completion has no focus session", failures: &failures)
        check(timer.phase == .completed, "break still completes", failures: &failures)
        check(timer.tick(at: origin.addingTimeInterval(21)) == nil, "completed break stays session-free", failures: &failures)
    }

    private static func testElapsedPauseCanStillDeliverOneSession(failures: inout Int) {
        var timer = TimerState(mode: .focus, duration: 30)
        timer.start(at: origin)
        timer.pause(at: origin.addingTimeInterval(40))

        check(timer.phase == .completed, "pause after deadline completes timer", failures: &failures)
        let session = timer.tick(at: origin.addingTimeInterval(41))
        check(session?.completedAt == origin.addingTimeInterval(30), "late pause preserves deadline as completion time", failures: &failures)
        check(timer.tick(at: origin.addingTimeInterval(42)) == nil, "late pause completion emits once", failures: &failures)
    }

    private static func testInvalidAndCorruptStateNormalization(failures: inout Int) {
        check(TimerState(mode: .focus, duration: 0).duration == TimerMode.focus.defaultDuration, "zero duration uses default", failures: &failures)
        check(TimerState(mode: .shortBreak, duration: -1).duration == TimerMode.shortBreak.defaultDuration, "negative duration uses default", failures: &failures)
        check(TimerState(mode: .longBreak, duration: .infinity).duration == TimerMode.longBreak.defaultDuration, "infinite duration uses default", failures: &failures)
        check(TimerState(mode: .focus, duration: 0.25).duration == TimerState.minimumDuration, "small positive duration uses lower bound", failures: &failures)
        check(TimerState(mode: .focus, duration: TimerState.maximumDuration * 2).duration == TimerState.maximumDuration, "large duration uses upper bound", failures: &failures)

        do {
            let incompleteRunning = Data("{\"mode\":\"focus\",\"phase\":\"running\",\"duration\":90,\"remaining\":60}".utf8)
            let normalized = try JSONDecoder().decode(TimerState.self, from: incompleteRunning)
            check(normalized.phase == .ready, "incomplete running archive resets to ready", failures: &failures)
            check(normalized.remaining == 90, "incomplete running archive restores duration", failures: &failures)

            let invalidValues = Data("{\"mode\":\"shortBreak\",\"phase\":\"ready\",\"duration\":-1,\"remaining\":999999}".utf8)
            let repaired = try JSONDecoder().decode(TimerState.self, from: invalidValues)
            check(repaired.duration == TimerMode.shortBreak.defaultDuration, "corrupt duration restores mode default", failures: &failures)
            check(repaired.remaining == TimerMode.shortBreak.defaultDuration, "ready archive normalizes remaining", failures: &failures)

            let invalidMode = Data("{\"mode\":\"unknown\",\"phase\":\"ready\",\"duration\":10,\"remaining\":10}".utf8)
            let fallback = try JSONDecoder().decode(TimerState.self, from: invalidMode)
            check(fallback.mode == .focus, "unknown mode falls back to focus", failures: &failures)
        } catch {
            fail("corrupt-state normalization threw \(error)", failures: &failures)
        }
    }

    private static func approximately(_ actual: TimeInterval, _ expected: TimeInterval, tolerance: TimeInterval = 0.000_1) -> Bool {
        abs(actual - expected) <= tolerance
    }

    private static func check(_ condition: @autoclosure () -> Bool, _ message: String, failures: inout Int) {
        if !condition() {
            fail(message, failures: &failures)
        }
    }

    private static func fail(_ message: String, failures: inout Int) {
        failures += 1
        fputs("FAIL: \(message)\n", stderr)
    }
}
