// test-inspiration.swift
// Generated by Codex (gpt-5.6-terra) on 2026-09-15.

import Foundation

@main
struct InspirationTestRunner {
    static func main() {
        var failures: [String] = []

        testValidDecodeAndEncode(failures: &failures)
        testUnknownMetadataIsAccepted(failures: &failures)
        testInvalidCatalogsAreRejected(failures: &failures)
        testUnicodeAndNewlineText(failures: &failures)
        testDefaultPhrasesAreCompactAndGeneric(failures: &failures)

        if failures.isEmpty {
            print("Inspiration checks passed: 5 test groups")
        } else {
            print("Inspiration checks failed: \(failures.count) assertion(s)")
            for failure in failures { print("FAIL: \(failure)") }
            exit(1)
        }
    }

    private static func testValidDecodeAndEncode(failures: inout [String]) {
        let expected = [
            Inspiration(id: "pause", text: "Pause and notice.", source: "Still"),
            Inspiration(id: "step", text: "Take the next small step.")
        ]
        do {
            let catalog = InspirationCatalog(phrases: expected)
            let data = try catalog.encoded()
            let decoded = try InspirationCatalog.decode(data)
            check(decoded.version == 1, "encoded catalog uses version 1", failures: &failures)
            check(decoded.phrases == expected, "valid catalog preserves each phrase", failures: &failures)
        } catch {
            failures.append("valid encode/decode threw \(error)")
        }
    }

    private static func testUnknownMetadataIsAccepted(failures: inout [String]) {
        let object: [String: Any] = [
            "version": 1,
            "phrases": [["id": "calm", "text": "Settle into this minute."]],
            "provenance": ["exportedBy": "local-device", "savedAt": "2026-09-15"],
            "notes": "Local metadata should not affect prompts."
        ]
        do {
            let decoded = try InspirationCatalog.decode(jsonData(object))
            check(decoded.phrases.count == 1 && decoded.phrases[0].id == "calm", "unknown catalog metadata is ignored", failures: &failures)
        } catch {
            failures.append("unknown metadata threw \(error)")
        }
    }

    private static func testInvalidCatalogsAreRejected(failures: inout [String]) {
        checkThrows(.emptyCatalog, "empty phrase list is rejected", failures: &failures) {
            _ = try InspirationCatalog.decode(jsonData(["version": 1, "phrases": []]))
        }
        checkThrows(.blankText("blank"), "blank text is rejected", failures: &failures) {
            _ = try InspirationCatalog.decode(jsonData([
                "version": 1,
                "phrases": [["id": "blank", "text": " \n\t "]]
            ]))
        }
        checkThrows(.duplicateIdentifier("same"), "duplicate identifiers are rejected", failures: &failures) {
            _ = try InspirationCatalog.decode(jsonData([
                "version": 1,
                "phrases": [["id": "same", "text": "First."], ["id": "same", "text": "Second."]]
            ]))
        }
        checkThrows(.textTooLong("long"), "text over 120 characters is rejected", failures: &failures) {
            _ = try InspirationCatalog.decode(jsonData([
                "version": 1,
                "phrases": [["id": "long", "text": String(repeating: "x", count: 121)]]
            ]))
        }
        checkThrows(.unsupportedVersion(2), "unsupported versions are rejected", failures: &failures) {
            _ = try InspirationCatalog.decode(jsonData(["version": 2, "phrases": [["id": "ok", "text": "Fine."]]]))
        }
        let tooManyPhrases = (0...100).map { ["id": "phrase-\($0)", "text": "A small pause."] }
        checkThrows(.tooManyPhrases, "more than 100 phrases are rejected", failures: &failures) {
            _ = try InspirationCatalog.decode(jsonData(["version": 1, "phrases": tooManyPhrases]))
        }
        checkThrows(.dataTooLarge, "input over 128 KB is rejected before parsing", failures: &failures) {
            _ = try InspirationCatalog.decode(Data(repeating: 0x20, count: 128 * 1024 + 1))
        }
    }

    private static func testUnicodeAndNewlineText(failures: inout [String]) {
        let text = "Breathe in 🌿\nBreathe out."
        do {
            let catalog = try InspirationCatalog.decode(jsonData([
                "version": 1,
                "phrases": [["id": "unicode", "text": text, "source": "Calm notes"]]
            ]))
            check(catalog.phrases[0].text == text, "Unicode and embedded newlines survive decoding", failures: &failures)
            check(catalog.phrases[0].text.count == text.count, "text bounds use user-visible characters", failures: &failures)
            checkThrows(.sourceTooLong("unicode"), "source labels over 120 characters are rejected", failures: &failures) {
                _ = try InspirationCatalog.decode(jsonData([
                    "version": 1,
                    "phrases": [["id": "unicode", "text": text, "source": String(repeating: "s", count: 121)]]
                ]))
            }
        } catch {
            failures.append("Unicode/newline handling threw \(error)")
        }
    }

    private static func testDefaultPhrasesAreCompactAndGeneric(failures: inout [String]) {
        let defaults = InspirationCatalog.defaults.phrases
        check(defaults.count == 6, "the fallback catalog contains six phrases", failures: &failures)
        check(defaults.allSatisfy { $0.text.count <= 75 }, "every fallback phrase fits the UI's compact prompt budget", failures: &failures)
        check(defaults.allSatisfy { $0.source == nil }, "fallback prompts contain no personal source attribution", failures: &failures)
    }

    private static func jsonData(_ object: Any) -> Data {
        try! JSONSerialization.data(withJSONObject: object, options: [.sortedKeys])
    }

    private static func check(_ condition: @autoclosure () -> Bool, _ message: String, failures: inout [String]) {
        if !condition() {
            failures.append(message)
        }
    }

    private static func checkThrows(
        _ expected: InspirationCatalogError,
        _ message: String,
        failures: inout [String],
        operation: () throws -> Void
    ) {
        do {
            try operation()
            failures.append("\(message): operation unexpectedly succeeded")
        } catch let error as InspirationCatalogError {
            if error != expected {
                failures.append("\(message): expected \(expected), got \(error)")
            }
        } catch {
            failures.append("\(message): expected InspirationCatalogError, got \(error)")
        }
    }
}
