// test-journal.swift
// Generated by Codex (gpt-5.6-terra) on 2026-09-15.

import Foundation

@main
struct MarkdownJournalTestRunner {
    static func main() {
        var failures: [String] = []
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("StillMarkdownJournalTests-\(UUID().uuidString)", isDirectory: true)

        do {
            try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
            defer { try? FileManager.default.removeItem(at: root) }

            testAppendPreservesHumanNotes(in: root, failures: &failures)
            testIdempotenceAndNoFalseDuplicate(in: root, failures: &failures)
            testTwoSessionsOnOneDay(in: root, failures: &failures)
            testReadRoundTrip(in: root, failures: &failures)
            testInvalidPathsAndWriteFailures(in: root, failures: &failures)
            testMalformedMetadataStopsWrites(in: root, failures: &failures)
        } catch {
            failures.append("Unable to prepare journal test directory: \(error)")
        }

        if failures.isEmpty {
            print("MarkdownJournal checks passed: 6 test groups")
        } else {
            print("MarkdownJournal checks failed: \(failures.count) assertion(s)")
            for failure in failures { print("FAIL: \(failure)") }
            exit(1)
        }
    }

    private static func testAppendPreservesHumanNotes(in root: URL, failures: inout [String]) {
        let url = root.appendingPathComponent("human-notes.md")
        let humanNotes = "# My focus notes\n\nI work best before lunch.\n"
        let session = makeSession(index: 1)

        do {
            try Data(humanNotes.utf8).write(to: url)
            try MarkdownJournal.synchronize(sessions: [session], to: url)
            let contents = try String(contentsOf: url, encoding: .utf8)
            check(contents.hasPrefix(humanNotes), "human notes remain an exact prefix", failures: &failures)
            check(contents.contains("Focus") && contents.contains("25 min"), "generated row is human-readable", failures: &failures)
            check(try MarkdownJournal.read(from: url) == [session], "appended metadata reads back", failures: &failures)
        } catch {
            failures.append("human-note preservation threw \(error)")
        }
    }

    private static func testIdempotenceAndNoFalseDuplicate(in root: URL, failures: inout [String]) {
        let url = root.appendingPathComponent("idempotence.md")
        let session = makeSession(index: 2)
        let humanText = "I typed still-session:\(session.id.uuidString) in a note; it is not metadata.\n"

        do {
            try Data(humanText.utf8).write(to: url)
            try MarkdownJournal.synchronize(sessions: [session], to: url)
            let once = try Data(contentsOf: url)
            try MarkdownJournal.synchronize(sessions: [session], to: url)
            let twice = try Data(contentsOf: url)

            check(once == twice, "repeated synchronize is byte-for-byte idempotent", failures: &failures)
            check(try MarkdownJournal.read(from: url).count == 1, "human marker-like text does not suppress a session", failures: &failures)
        } catch {
            failures.append("idempotence threw \(error)")
        }
    }

    private static func testTwoSessionsOnOneDay(in root: URL, failures: inout [String]) {
        let url = root.appendingPathComponent("two-sessions.md")
        let first = makeSession(index: 3)
        let second = FocusSession(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000004")!,
            startedAt: first.startedAt.addingTimeInterval(60 * 60),
            completedAt: first.completedAt.addingTimeInterval(60 * 60),
            duration: first.duration
        )

        do {
            try MarkdownJournal.synchronize(sessions: [first, second], to: url)
            let read = try MarkdownJournal.read(from: url)
            let contents = try String(contentsOf: url, encoding: .utf8)
            check(read == [first, second], "two same-day sessions retain order and identity", failures: &failures)
            check(occurrences(of: "<!-- still-session:", in: contents) == 2, "two rows contain two machine markers", failures: &failures)
        } catch {
            failures.append("two-session append threw \(error)")
        }
    }

    private static func testReadRoundTrip(in root: URL, failures: inout [String]) {
        let url = root.appendingPathComponent("round-trip.md")
        let session = FocusSession(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000005")!,
            startedAt: Date(timeIntervalSince1970: 1_789_123_456.75),
            completedAt: Date(timeIntervalSince1970: 1_789_125_001.125),
            duration: 1_500
        )

        do {
            try MarkdownJournal.synchronize(sessions: [session], to: url)
            check(try MarkdownJournal.read(from: url) == [session], "metadata round-trip preserves fractional dates", failures: &failures)
        } catch {
            failures.append("round-trip threw \(error)")
        }
    }

    private static func testInvalidPathsAndWriteFailures(in root: URL, failures: inout [String]) {
        let session = makeSession(index: 6)
        let textURL = root.appendingPathComponent("sessions.txt")
        let directoryURL = root.appendingPathComponent("directory.md", isDirectory: true)
        let blockingParent = root.appendingPathComponent("not-a-directory")

        do {
            try FileManager.default.createDirectory(at: directoryURL, withIntermediateDirectories: true)
            try Data("blocking parent".utf8).write(to: blockingParent)
            checkThrows(MarkdownJournalError.invalidExtension, "non-Markdown path is rejected", failures: &failures) {
                try MarkdownJournal.synchronize(sessions: [session], to: textURL)
            }
            checkThrows(MarkdownJournalError.notRegularFile, "Markdown directory is rejected", failures: &failures) {
                try MarkdownJournal.synchronize(sessions: [session], to: directoryURL)
            }
            checkThrows(nil, "a file used as a parent surfaces a write failure", failures: &failures) {
                try MarkdownJournal.synchronize(sessions: [session], to: blockingParent.appendingPathComponent("sessions.md"))
            }
        } catch {
            failures.append("invalid-path fixture threw \(error)")
        }
    }

    private static func testMalformedMetadataStopsWrites(in root: URL, failures: inout [String]) {
        let url = root.appendingPathComponent("malformed.md")
        let original = "# Notes\n\n<!-- still-session:not-valid-base64 -->\n"
        let session = makeSession(index: 7)

        do {
            try Data(original.utf8).write(to: url)
            checkThrows(MarkdownJournalError.malformedMetadata, "malformed metadata is reported by read", failures: &failures) {
                _ = try MarkdownJournal.read(from: url)
            }
            checkThrows(MarkdownJournalError.malformedMetadata, "malformed metadata blocks synchronize", failures: &failures) {
                try MarkdownJournal.synchronize(sessions: [session], to: url)
            }
            checkThrows(MarkdownJournalError.malformedMetadata, "failed synchronize releases its kernel lock", failures: &failures) {
                try MarkdownJournal.synchronize(sessions: [session], to: url)
            }
            check(!FileManager.default.fileExists(atPath: url.path + ".still.lock"), "journal never leaves a sidecar lock file", failures: &failures)
            check(try String(contentsOf: url, encoding: .utf8) == original, "malformed journal is never rewritten", failures: &failures)
        } catch {
            failures.append("malformed-metadata fixture threw \(error)")
        }
    }

    private static func makeSession(index: Int) -> FocusSession {
        let startedAt = Date(timeIntervalSince1970: 1_789_000_000 + TimeInterval(index * 3_600))
        return FocusSession(
            id: UUID(uuidString: String(format: "00000000-0000-0000-0000-%012d", index))!,
            startedAt: startedAt,
            completedAt: startedAt.addingTimeInterval(1_500),
            duration: 1_500
        )
    }

    private static func occurrences(of needle: String, in haystack: String) -> Int {
        var count = 0
        var searchRange = haystack.startIndex..<haystack.endIndex
        while let range = haystack.range(of: needle, range: searchRange) {
            count += 1
            searchRange = range.upperBound..<haystack.endIndex
        }
        return count
    }

    private static func check(_ condition: @autoclosure () throws -> Bool, _ message: String, failures: inout [String]) {
        do {
            if try !condition() {
                failures.append(message)
            }
        } catch {
            failures.append("\(message): \(error)")
        }
    }

    private static func checkThrows(
        _ expected: MarkdownJournalError?,
        _ message: String,
        failures: inout [String],
        operation: () throws -> Void
    ) {
        do {
            try operation()
            failures.append("\(message): operation unexpectedly succeeded")
        } catch let error as MarkdownJournalError {
            if let expected, error != expected {
                failures.append("\(message): expected \(expected), got \(error)")
            }
        } catch {
            if expected != nil {
                failures.append("\(message): expected MarkdownJournalError, got \(error)")
            }
        }
    }
}
