#!/bin/sh
# test-inspiration.sh
# Generated by Codex (gpt-5.6-terra) on 2026-09-15.
# Runs Inspiration checks without Swift Package Manager or XCTest.

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
TEMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/still-inspiration-tests.XXXXXX")
trap 'rm -rf "$TEMP_DIR"' EXIT HUP INT TERM
export CLANG_MODULE_CACHE_PATH="$TEMP_DIR/module-cache"

swiftc \
    "$PROJECT_ROOT/Sources/StillCore/Inspiration.swift" \
    "$SCRIPT_DIR/test-inspiration.swift" \
    -o "$TEMP_DIR/test-inspiration"

"$TEMP_DIR/test-inspiration"
