#!/bin/sh
# test-journal.sh
# Generated by Codex (gpt-5.6-terra) on 2026-09-15.
# Runs MarkdownJournal checks without Swift Package Manager or XCTest.

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
TEMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/still-journal-tests.XXXXXX")
trap 'rm -rf "$TEMP_DIR"' EXIT HUP INT TERM

swiftc \
    "$PROJECT_ROOT/Sources/StillCore/StillCore.swift" \
    "$PROJECT_ROOT/Sources/StillCore/MarkdownJournal.swift" \
    "$SCRIPT_DIR/test-journal.swift" \
    -o "$TEMP_DIR/test-journal"

"$TEMP_DIR/test-journal"
