// Inspiration.swift
// Generated by Codex (gpt-5.6-terra) on 2026-09-15.

import Foundation

/// A short, optional attribution attached to a gentle focus prompt.
public struct Inspiration: Codable, Equatable, Sendable {
    public let id: String
    public let text: String
    public let source: String?

    public init(id: String, text: String, source: String? = nil) {
        self.id = id
        self.text = text
        self.source = source
    }
}

public enum InspirationCatalogError: Error, Equatable, Sendable {
    case dataTooLarge
    case unsupportedVersion(Int)
    case emptyCatalog
    case tooManyPhrases
    case blankIdentifier
    case duplicateIdentifier(String)
    case blankText(String)
    case textTooLong(String)
    case sourceTooLong(String)
}

/// A bounded, local collection of prompts. Its wire format is version 1 JSON.
public struct InspirationCatalog: Codable, Sendable {
    public let version: Int
    public let phrases: [Inspiration]

    private static let supportedVersion = 1
    private static let maximumPhraseCount = 100
    private static let maximumTextLength = 120
    private static let maximumSourceLength = 120
    private static let maximumDataLength = 128 * 1024

    public init(phrases: [Inspiration]) {
        self.version = Self.supportedVersion
        self.phrases = phrases
    }

    /// Built-in prompts are deliberately generic so the app can be shared publicly.
    public static var defaults: InspirationCatalog {
        InspirationCatalog(phrases: [
            Inspiration(id: "one-small-breath", text: "Take one small breath, then meet the next moment gently."),
            Inspiration(id: "be-here", text: "You do not have to hurry to be here."),
            Inspiration(id: "already-steady", text: "Let your attention rest on what is already steady."),
            Inspiration(id: "kindest-useful-thing", text: "Begin with the kindest useful thing."),
            Inspiration(id: "quiet-pause", text: "A quiet pause can make room for a clear next step."),
            Inspiration(id: "honest-presence", text: "This moment asks only for your honest presence.")
        ])
    }

    public static func decode(_ data: Data) throws -> InspirationCatalog {
        guard data.count <= Self.maximumDataLength else {
            throw InspirationCatalogError.dataTooLarge
        }
        return try JSONDecoder().decode(Self.self, from: data)
    }

    public func encoded() throws -> Data {
        try Self.validate(phrases)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        let data = try encoder.encode(self)
        guard data.count <= Self.maximumDataLength else {
            throw InspirationCatalogError.dataTooLarge
        }
        return data
    }

    private enum CodingKeys: String, CodingKey {
        case version
        case phrases
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let version = try container.decode(Int.self, forKey: .version)
        guard version == Self.supportedVersion else {
            throw InspirationCatalogError.unsupportedVersion(version)
        }
        guard let phrases = try container.decodeIfPresent([Inspiration].self, forKey: .phrases) else {
            throw InspirationCatalogError.emptyCatalog
        }
        try Self.validate(phrases)

        self.version = version
        self.phrases = phrases
    }

    private static func validate(_ phrases: [Inspiration]) throws {
        guard !phrases.isEmpty else {
            throw InspirationCatalogError.emptyCatalog
        }
        guard phrases.count <= Self.maximumPhraseCount else {
            throw InspirationCatalogError.tooManyPhrases
        }

        var identifiers = Set<String>()
        for phrase in phrases {
            guard !phrase.id.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
                throw InspirationCatalogError.blankIdentifier
            }
            guard identifiers.insert(phrase.id).inserted else {
                throw InspirationCatalogError.duplicateIdentifier(phrase.id)
            }
            guard !phrase.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
                throw InspirationCatalogError.blankText(phrase.id)
            }
            guard phrase.text.count <= Self.maximumTextLength else {
                throw InspirationCatalogError.textTooLong(phrase.id)
            }
            if let source = phrase.source, source.count > Self.maximumSourceLength {
                throw InspirationCatalogError.sourceTooLong(phrase.id)
            }
        }
    }
}
