// MarkdownJournal.swift
// Generated by Codex (gpt-5.6-terra) on 2026-09-15.

import Foundation
import Darwin

@_silgen_name("flock")
private func systemFlock(_ descriptor: Int32, _ operation: Int32) -> Int32

/// Errors raised while reading or appending Still session metadata in a Markdown file.
public enum MarkdownJournalError: Error, Equatable, LocalizedError, Sendable {
    case invalidExtension
    case notRegularFile
    case notWritable
    case malformedMetadata
    case lockUnavailable

    public var errorDescription: String? {
        switch self {
        case .invalidExtension:
            return "A Still journal must use the .md extension."
        case .notRegularFile:
            return "The Still journal path must be a regular file."
        case .notWritable:
            return "The Still journal file is not writable."
        case .malformedMetadata:
            return "The Still journal contains malformed session metadata."
        case .lockUnavailable:
            return "The Still journal is busy and could not be locked for writing."
        }
    }
}

/// Appends completed focus sessions to a user-owned Markdown journal.
///
/// Each generated row embeds the canonical session as base64 JSON in an HTML comment.
/// Markdown outside those comments is never parsed as session data or rewritten.
public enum MarkdownJournal {
    private static let header = "# Focus sessions\n\nCompleted focus sessions, recorded locally by Still.\n"
    private static let markerPrefix = "<!-- still-session:"
    private static let markerSuffix = "-->"

    /// Reads all session rows embedded in a journal, preserving their document order.
    public static func read(from url: URL) throws -> [FocusSession] {
        try validateJournalURL(url, requireExistingFile: true)
        let contents = try String(contentsOf: url, encoding: .utf8)
        return try sessions(in: contents)
    }

    /// Creates a journal when necessary, then appends only sessions whose IDs are not
    /// already represented by valid Still metadata in the document.
    public static func synchronize(sessions newSessions: [FocusSession], to url: URL) throws {
        try validateJournalURL(url, requireExistingFile: false)
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)

        try withLockedJournal(at: url) { handle, created in
            let contents = try readContents(from: handle)
            let existingSessions = try sessions(in: contents)
            var knownIDs = Set(existingSessions.map(\.id))
            let missing = newSessions.filter { knownIDs.insert($0.id).inserted }
            guard !missing.isEmpty else { return }

            let rows = try missing.map { try row(for: $0) }.joined(separator: "\n") + "\n"
            let separator: String
            if created || contents == header {
                separator = "\n"
            } else if contents.isEmpty || contents.hasSuffix("\n") {
                separator = ""
            } else {
                separator = "\n"
            }
            try append(Data((separator + rows).utf8), to: handle)
        }
    }

    private static func append(_ data: Data, to handle: FileHandle) throws {
        try handle.seekToEnd()
        try handle.write(contentsOf: data)
        try handle.synchronize()
    }

    /// Opens with `O_NOFOLLOW`, validates the actual descriptor with `fstat`, and takes
    /// an immediate nonblocking advisory lock. Closing the descriptor always releases
    /// that lock, including after an error or process exit.
    private static func withLockedJournal<T>(at url: URL, operation: (FileHandle, Bool) throws -> T) throws -> T {
        let opened = try openJournalDescriptor(at: url)
        defer { Darwin.close(opened.descriptor) }

        guard systemFlock(opened.descriptor, Int32(LOCK_EX | LOCK_NB)) == 0 else {
            if errno == EWOULDBLOCK || errno == EAGAIN {
                throw MarkdownJournalError.lockUnavailable
            }
            throw currentPOSIXError()
        }

        let handle = FileHandle(fileDescriptor: opened.descriptor, closeOnDealloc: false)
        if opened.created {
            try handle.write(contentsOf: Data(header.utf8))
            try handle.synchronize()
        }
        return try operation(handle, opened.created)
    }

    private static func openJournalDescriptor(at url: URL) throws -> (descriptor: Int32, created: Bool) {
        let existingFlags = O_RDWR | O_CLOEXEC | O_NOFOLLOW
        let createFlags = existingFlags | O_CREAT | O_EXCL
        let descriptor = url.path.withCString { path in
            Darwin.open(path, createFlags, S_IRUSR | S_IWUSR)
        }

        if descriptor >= 0 {
            try validateRegularDescriptor(descriptor)
            return (descriptor, true)
        }

        guard errno == EEXIST else {
            throw journalOpenError(for: errno)
        }

        let existingDescriptor = url.path.withCString { path in
            Darwin.open(path, existingFlags)
        }
        guard existingDescriptor >= 0 else {
            throw journalOpenError(for: errno)
        }
        do {
            try validateRegularDescriptor(existingDescriptor)
            return (existingDescriptor, false)
        } catch {
            Darwin.close(existingDescriptor)
            throw error
        }
    }

    private static func validateRegularDescriptor(_ descriptor: Int32) throws {
        var status = stat()
        guard Darwin.fstat(descriptor, &status) == 0 else {
            throw currentPOSIXError()
        }
        guard (status.st_mode & S_IFMT) == S_IFREG else {
            throw MarkdownJournalError.notRegularFile
        }
    }

    private static func readContents(from handle: FileHandle) throws -> String {
        try handle.seek(toOffset: 0)
        let data = try handle.readToEnd() ?? Data()
        guard let contents = String(data: data, encoding: .utf8) else {
            throw CocoaError(.fileReadInapplicableStringEncoding)
        }
        return contents
    }

    private static func journalOpenError(for code: Int32) -> Swift.Error {
        switch code {
        case ELOOP, EISDIR:
            return MarkdownJournalError.notRegularFile
        case EACCES, EROFS:
            return MarkdownJournalError.notWritable
        default:
            return POSIXError(POSIXErrorCode(rawValue: code) ?? .EIO)
        }
    }

    private static func currentPOSIXError() -> POSIXError {
        POSIXError(POSIXErrorCode(rawValue: errno) ?? .EIO)
    }

    private static func validateJournalURL(_ url: URL, requireExistingFile: Bool) throws {
        guard url.pathExtension.lowercased() == "md" else {
            throw MarkdownJournalError.invalidExtension
        }

        let fileManager = FileManager.default
        guard fileManager.fileExists(atPath: url.path) else {
            if requireExistingFile {
                throw CocoaError(.fileNoSuchFile)
            }
            return
        }

        let values = try url.resourceValues(forKeys: [.isRegularFileKey, .isSymbolicLinkKey])
        guard values.isRegularFile == true, values.isSymbolicLink != true else {
            throw MarkdownJournalError.notRegularFile
        }
    }

    private static func sessions(in contents: String) throws -> [FocusSession] {
        var result: [FocusSession] = []
        var searchRange = contents.startIndex..<contents.endIndex

        while let markerRange = contents.range(of: markerPrefix, options: [], range: searchRange) {
            let metadataStart = markerRange.upperBound
            guard let endingRange = contents.range(of: markerSuffix, options: [], range: metadataStart..<contents.endIndex) else {
                throw MarkdownJournalError.malformedMetadata
            }

            let encoded = contents[metadataStart..<endingRange.lowerBound]
                .trimmingCharacters(in: .whitespacesAndNewlines)
            guard let data = Data(base64Encoded: encoded),
                  let session = try? JSONDecoder().decode(FocusSession.self, from: data) else {
                throw MarkdownJournalError.malformedMetadata
            }
            result.append(session)
            searchRange = endingRange.upperBound..<contents.endIndex
        }

        return result
    }

    private static func row(for session: FocusSession) throws -> String {
        let display = sessionDisplay(session)
        let metadata = try JSONEncoder().encode(session).base64EncodedString()
        return "- **\(display.timeRange)** · Focus · **\(display.duration)** <!-- still-session:\(metadata) -->"
    }

    private static func sessionDisplay(_ session: FocusSession) -> (timeRange: String, duration: String) {
        let calendar = Calendar.current
        let zone = TimeZone.current
        let zoneLabel = zone.abbreviation(for: session.startedAt) ?? zone.identifier
        let dateFormatter = DateFormatter()
        dateFormatter.locale = Locale(identifier: "en_US_POSIX")
        dateFormatter.timeZone = zone

        if calendar.isDate(session.startedAt, inSameDayAs: session.completedAt) {
            dateFormatter.dateFormat = "yyyy-MM-dd"
            let day = dateFormatter.string(from: session.startedAt)
            dateFormatter.dateFormat = "HH:mm"
            let start = dateFormatter.string(from: session.startedAt)
            let end = dateFormatter.string(from: session.completedAt)
            return ("\(day) \(start)–\(end) \(zoneLabel)", durationDescription(session.duration))
        }

        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm zzz"
        let start = dateFormatter.string(from: session.startedAt)
        let end = dateFormatter.string(from: session.completedAt)
        return ("\(start)–\(end)", durationDescription(session.duration))
    }

    private static func durationDescription(_ duration: TimeInterval) -> String {
        let minutes = max(1, Int((duration / 60).rounded()))
        let hours = minutes / 60
        let remainingMinutes = minutes % 60
        if hours == 0 {
            return "\(minutes) min"
        }
        if remainingMinutes == 0 {
            return "\(hours) hr"
        }
        return "\(hours) hr \(remainingMinutes) min"
    }
}
