// StillCore.swift
// Generated by Codex (gpt-5.6-terra) on 2026-09-15.

import Foundation

/// The kind of interval the timer is currently configured to run.
public enum TimerMode: String, Codable, CaseIterable, Sendable {
    case focus
    case shortBreak
    case longBreak

    public var title: String {
        switch self {
        case .focus:
            return "Focus"
        case .shortBreak:
            return "Short Break"
        case .longBreak:
            return "Long Break"
        }
    }

    public var defaultDuration: TimeInterval {
        switch self {
        case .focus:
            return 25 * 60
        case .shortBreak:
            return 5 * 60
        case .longBreak:
            return 15 * 60
        }
    }
}

/// The lifecycle stage of a timer interval.
public enum TimerPhase: String, Codable, Sendable {
    case ready
    case running
    case paused
    case completed
}

/// A completed focus interval suitable for archival.
public struct FocusSession: Codable, Identifiable, Equatable, Sendable {
    public let id: UUID
    public let startedAt: Date
    public let completedAt: Date
    public let duration: TimeInterval

    public init(id: UUID, startedAt: Date, completedAt: Date, duration: TimeInterval) {
        self.id = id
        self.startedAt = startedAt
        self.completedAt = completedAt
        self.duration = duration
    }
}

/// A date-based, pause-aware timer state machine.
///
/// Running timers use an absolute deadline rather than decrementing a counter.
/// Consequently, `remaining(at:)` is accurate after sleep, wake, and app relaunch.
public struct TimerState: Codable, Sendable {
    /// A custom duration is bounded to prevent corrupt persisted values from creating
    /// unusable timers. Zero, negative, and non-finite values restore the mode default.
    public static let minimumDuration: TimeInterval = 1
    public static let maximumDuration: TimeInterval = 24 * 60 * 60

    public private(set) var mode: TimerMode
    public private(set) var phase: TimerPhase
    public private(set) var duration: TimeInterval
    public private(set) var remaining: TimeInterval
    public private(set) var startedAt: Date?
    public private(set) var deadline: Date?
    public private(set) var sessionID: UUID?

    // Completion metadata is private implementation state.  Persisting it lets a
    // completed timer remain idempotent after it is restored from disk.
    private var completionDate: Date?
    private var completionDelivered: Bool

    public init(mode: TimerMode = .focus, duration: TimeInterval? = nil) {
        let normalizedDuration = Self.normalizedDuration(duration, for: mode)
        self.mode = mode
        self.phase = .ready
        self.duration = normalizedDuration
        self.remaining = normalizedDuration
        self.startedAt = nil
        self.deadline = nil
        self.sessionID = nil
        self.completionDate = nil
        self.completionDelivered = true
    }

    /// Begins a new interval or resumes a paused one. Repeated starts while already
    /// running, or starts after completion, do not alter the state.
    public mutating func start(at date: Date) {
        switch phase {
        case .ready:
            phase = .running
            startedAt = date
            deadline = date.addingTimeInterval(remaining)
            sessionID = mode == .focus ? UUID() : nil
            completionDate = nil
            completionDelivered = true

        case .paused:
            phase = .running
            deadline = date.addingTimeInterval(remaining)
            if startedAt == nil {
                startedAt = date
            }
            if mode == .focus && sessionID == nil {
                sessionID = UUID()
            }

        case .running, .completed:
            break
        }
    }

    /// Stops the clock while preserving the remaining time and original start date.
    /// If the deadline has already passed, the interval is marked completed; a
    /// subsequent `tick(at:)` emits its focus session once, if applicable.
    public mutating func pause(at date: Date) {
        guard phase == .running else { return }

        let updatedRemaining = remaining(at: date)
        if updatedRemaining == 0 {
            complete(at: deadline ?? date)
            return
        }

        remaining = updatedRemaining
        deadline = nil
        phase = .paused
    }

    /// Cancels the current interval while retaining the configured mode and duration.
    public mutating func reset() {
        phase = .ready
        remaining = duration
        startedAt = nil
        deadline = nil
        sessionID = nil
        completionDate = nil
        completionDelivered = true
    }

    /// Selects a new interval type and starts it in the ready state.
    public mutating func configure(mode: TimerMode, duration: TimeInterval) {
        self.mode = mode
        self.duration = Self.normalizedDuration(duration, for: mode)
        reset()
    }

    /// Calculates the remaining interval at a given instant without mutating state.
    public func remaining(at date: Date) -> TimeInterval {
        guard phase == .running, let deadline else {
            return Self.clampedRemaining(remaining, duration: duration)
        }

        return Self.clampedRemaining(deadline.timeIntervalSince(date), duration: duration)
    }

    /// Updates a running timer and returns its completed focus session exactly once.
    /// Break completion changes the timer phase but never creates a session.
    public mutating func tick(at date: Date) -> FocusSession? {
        if phase == .completed {
            return deliverCompletionIfNeeded()
        }

        guard phase == .running else { return nil }

        let updatedRemaining = remaining(at: date)
        remaining = updatedRemaining
        guard updatedRemaining == 0 else { return nil }

        complete(at: deadline ?? date)
        return deliverCompletionIfNeeded()
    }

    private mutating func complete(at date: Date) {
        remaining = 0
        deadline = nil
        phase = .completed
        completionDate = date
        completionDelivered = mode != .focus
    }

    private mutating func deliverCompletionIfNeeded() -> FocusSession? {
        guard mode == .focus, !completionDelivered else { return nil }

        completionDelivered = true
        guard let id = sessionID, let startedAt, let completedAt = completionDate else {
            return nil
        }

        return FocusSession(
            id: id,
            startedAt: startedAt,
            completedAt: completedAt,
            duration: duration
        )
    }

    private static func normalizedDuration(_ candidate: TimeInterval?, for mode: TimerMode) -> TimeInterval {
        guard let candidate, candidate.isFinite, candidate > 0 else {
            return mode.defaultDuration
        }

        return min(max(candidate, minimumDuration), maximumDuration)
    }

    private static func clampedRemaining(_ value: TimeInterval, duration: TimeInterval) -> TimeInterval {
        guard value.isFinite else { return value.sign == .minus ? 0 : duration }
        return min(max(value, 0), duration)
    }

    private enum CodingKeys: String, CodingKey {
        case mode
        case phase
        case duration
        case remaining
        case startedAt
        case deadline
        case sessionID
        case completionDate
        case completionDelivered
    }

    /// Restores a persisted state defensively. Malformed durations and incomplete
    /// active intervals normalize to a safe ready state instead of running forever.
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let decodedMode = (try? container.decode(TimerMode.self, forKey: .mode)) ?? .focus
        let decodedPhase = (try? container.decode(TimerPhase.self, forKey: .phase)) ?? .ready
        let decodedDuration = try? container.decode(TimeInterval.self, forKey: .duration)

        self.mode = decodedMode
        self.phase = decodedPhase
        self.duration = Self.normalizedDuration(decodedDuration, for: decodedMode)
        self.remaining = Self.clampedRemaining(
            (try? container.decode(TimeInterval.self, forKey: .remaining)) ?? self.duration,
            duration: self.duration
        )
        self.startedAt = try? container.decode(Date.self, forKey: .startedAt)
        self.deadline = try? container.decode(Date.self, forKey: .deadline)
        self.sessionID = try? container.decode(UUID.self, forKey: .sessionID)
        self.completionDate = try? container.decode(Date.self, forKey: .completionDate)
        // Older archives did not store delivery state. Treat them as already delivered
        // so restoring an old completed timer cannot create a duplicate session.
        self.completionDelivered = (try? container.decode(Bool.self, forKey: .completionDelivered)) ?? true
        normalizeRestoredState()
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mode, forKey: .mode)
        try container.encode(phase, forKey: .phase)
        try container.encode(duration, forKey: .duration)
        try container.encode(remaining, forKey: .remaining)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encodeIfPresent(deadline, forKey: .deadline)
        try container.encodeIfPresent(sessionID, forKey: .sessionID)
        try container.encodeIfPresent(completionDate, forKey: .completionDate)
        try container.encode(completionDelivered, forKey: .completionDelivered)
    }

    private mutating func normalizeRestoredState() {
        switch phase {
        case .ready:
            remaining = duration
            startedAt = nil
            deadline = nil
            sessionID = nil
            completionDate = nil
            completionDelivered = true

        case .running:
            guard deadline != nil, startedAt != nil else {
                reset()
                return
            }
            if mode != .focus {
                sessionID = nil
            } else if sessionID == nil {
                reset()
            }
            completionDate = nil
            completionDelivered = true

        case .paused:
            deadline = nil
            completionDate = nil
            completionDelivered = true
            guard startedAt != nil else {
                reset()
                return
            }
            if mode != .focus {
                sessionID = nil
            } else if sessionID == nil {
                reset()
            }

        case .completed:
            remaining = 0
            deadline = nil
            if mode != .focus {
                sessionID = nil
                completionDelivered = true
            } else if !completionDelivered,
                      (sessionID == nil || startedAt == nil || completionDate == nil) {
                // A malformed pending completion must not repeatedly attempt delivery.
                completionDelivered = true
            }
        }
    }
}
