// TimerStateTests.swift
// Generated by Codex (gpt-5.6-terra) on 2026-09-15.

import Foundation
import XCTest
@testable import StillCore

final class TimerStateTests: XCTestCase {
    private let origin = Date(timeIntervalSinceReferenceDate: 1_000_000)

    func testModeMetadataUsesPomodoroDefaults() {
        XCTAssertEqual(TimerMode.focus.title, "Focus")
        XCTAssertEqual(TimerMode.shortBreak.title, "Short Break")
        XCTAssertEqual(TimerMode.longBreak.title, "Long Break")
        XCTAssertEqual(TimerMode.focus.defaultDuration, 30 * 60)
        XCTAssertEqual(TimerMode.shortBreak.defaultDuration, 5 * 60)
        XCTAssertEqual(TimerMode.longBreak.defaultDuration, 15 * 60)
    }

    func testStartUsesAnAbsoluteDeadline() {
        var timer = TimerState(mode: .focus, duration: 120)

        timer.start(at: origin)

        XCTAssertEqual(timer.phase, .running)
        XCTAssertEqual(timer.startedAt, origin)
        XCTAssertEqual(timer.deadline, origin.addingTimeInterval(120))
        XCTAssertNotNil(timer.sessionID)
        XCTAssertEqual(timer.remaining(at: origin.addingTimeInterval(35)), 85, accuracy: 0.000_1)
    }

    func testPauseAndResumePreserveElapsedFocusStart() {
        var timer = TimerState(mode: .focus, duration: 120)
        timer.start(at: origin)

        timer.pause(at: origin.addingTimeInterval(30))

        XCTAssertEqual(timer.phase, .paused)
        XCTAssertEqual(timer.remaining, 90, accuracy: 0.000_1)
        XCTAssertNil(timer.deadline)
        XCTAssertEqual(timer.startedAt, origin)

        let resumedAt = origin.addingTimeInterval(1_000)
        timer.start(at: resumedAt)

        XCTAssertEqual(timer.phase, .running)
        XCTAssertEqual(timer.startedAt, origin)
        XCTAssertEqual(timer.deadline, resumedAt.addingTimeInterval(90))
        XCTAssertEqual(timer.remaining(at: resumedAt.addingTimeInterval(20)), 70, accuracy: 0.000_1)
    }

    func testFocusCompletionCreatesOneSessionAtTheDeadline() {
        var timer = TimerState(mode: .focus, duration: 120)
        timer.start(at: origin)
        let id = try! XCTUnwrap(timer.sessionID)

        XCTAssertNil(timer.tick(at: origin.addingTimeInterval(119)))
        let session = try! XCTUnwrap(timer.tick(at: origin.addingTimeInterval(200)))

        XCTAssertEqual(timer.phase, .completed)
        XCTAssertEqual(timer.remaining, 0)
        XCTAssertEqual(session.id, id)
        XCTAssertEqual(session.startedAt, origin)
        XCTAssertEqual(session.completedAt, origin.addingTimeInterval(120))
        XCTAssertEqual(session.duration, 120)
        XCTAssertNil(timer.tick(at: origin.addingTimeInterval(201)))
    }

    func testCompletionIsStillIdempotentAfterRestoration() throws {
        var timer = TimerState(mode: .focus, duration: 60)
        timer.start(at: origin)
        XCTAssertNotNil(timer.tick(at: origin.addingTimeInterval(61)))

        let restored = try JSONDecoder().decode(TimerState.self, from: JSONEncoder().encode(timer))

        var copy = restored
        XCTAssertEqual(copy.phase, .completed)
        XCTAssertNil(copy.tick(at: origin.addingTimeInterval(100)))
    }

    func testRunningTimerRestoresItsDeadlineAfterRelaunch() throws {
        var timer = TimerState(mode: .focus, duration: 120)
        timer.start(at: origin)
        _ = timer.tick(at: origin.addingTimeInterval(30))

        var restored = try JSONDecoder().decode(TimerState.self, from: JSONEncoder().encode(timer))

        XCTAssertEqual(restored.phase, .running)
        XCTAssertEqual(restored.remaining(at: origin.addingTimeInterval(80)), 40, accuracy: 0.000_1)
        XCTAssertNotNil(restored.tick(at: origin.addingTimeInterval(121)))
    }

    func testResetAndConfigureCancelAnInProgressFocusSession() {
        var timer = TimerState(mode: .focus, duration: 90)
        timer.start(at: origin)
        timer.reset()

        XCTAssertEqual(timer.phase, .ready)
        XCTAssertEqual(timer.remaining, 90)
        XCTAssertNil(timer.startedAt)
        XCTAssertNil(timer.deadline)
        XCTAssertNil(timer.sessionID)

        timer.configure(mode: .longBreak, duration: 45)

        XCTAssertEqual(timer.mode, .longBreak)
        XCTAssertEqual(timer.duration, 45)
        XCTAssertEqual(timer.remaining, 45)
        XCTAssertEqual(timer.phase, .ready)
    }

    func testBreakCompletionNeverReturnsAFocusSession() {
        var timer = TimerState(mode: .shortBreak, duration: 20)
        timer.start(at: origin)

        XCTAssertNil(timer.sessionID)
        XCTAssertNil(timer.tick(at: origin.addingTimeInterval(20)))
        XCTAssertEqual(timer.phase, .completed)
        XCTAssertNil(timer.tick(at: origin.addingTimeInterval(21)))
    }

    func testInvalidDurationsUseDefaultsAndBounds() {
        XCTAssertEqual(TimerState(mode: .focus, duration: 0).duration, TimerMode.focus.defaultDuration)
        XCTAssertEqual(TimerState(mode: .shortBreak, duration: -1).duration, TimerMode.shortBreak.defaultDuration)
        XCTAssertEqual(TimerState(mode: .longBreak, duration: .infinity).duration, TimerMode.longBreak.defaultDuration)
        XCTAssertEqual(TimerState(mode: .focus, duration: 0.25).duration, TimerState.minimumDuration)
        XCTAssertEqual(
            TimerState(mode: .focus, duration: TimerState.maximumDuration * 2).duration,
            TimerState.maximumDuration
        )
    }

    func testIncompleteRunningStateNormalizesToReadyOnDecode() throws {
        let data = Data("""
        {"mode":"focus","phase":"running","duration":90,"remaining":60}
        """.utf8)

        let restored = try JSONDecoder().decode(TimerState.self, from: data)

        XCTAssertEqual(restored.phase, .ready)
        XCTAssertEqual(restored.remaining, 90)
        XCTAssertNil(restored.startedAt)
        XCTAssertNil(restored.deadline)
    }
}
